mylist = ["prashant", "Ashish", "komal", "ankush", "Ashish", 77, "sandip" , 60.52, "prashant"]  
print(mylist)  
print(type(mylist))  
print(mylist[0])  
print(mylist[1])   
print(mylist[2])  
print(mylist[-1])  
print(mylist[2:5])  
print(mylist[:5])   
print(mylist[1:])  
print(mylist[1:8:2])  
print(mylist[:])
print(mylist[::-1])