print(bool(0)) #false
print(bool(15)) #true
print(bool(3.14)) #true
print(bool(0.0)) #false
print(bool(1+2j)) #true
print(bool(-1)) #true
print(bool(False)) #false
print(bool(True)) #true
print(bool("")) #false
